import { useAsyncData, type RouteMiddleware } from 'nuxt/app';
import {
	getContentItemByPath20,
	type IApiContentResponseModelReadable
} from '~/.umbraco';

/**
 * Nuxt middleware to inject the requested Umbraco content item into the route
 * object.
 */
const middleware: RouteMiddleware = async (to) => {
	const { data, error } = await useAsyncData(to.path, () =>
		getContent(to.path)
	);

	if (error.value) {
		throw error.value;
	}

	to.meta.content = data.value;
};

export default middleware;

/**
 * Returns the Umbraco content item for a given path by calling the API client
 * generated by openapi-typescript.
 * @param path - The path.
 * @returns The content item, or null.
 */
const getContent = async (
	path: string
): Promise<IApiContentResponseModelReadable> => {
	const { data, error } = await getContentItemByPath20({
		path: { path }
	});

	if (error) {
		throw createError({
			statusCode: error.status ?? 500,
			statusMessage: error.title ?? 'Unknown error'
		});
	}

	return data;
};
