import { useAsyncData, type RouteMiddleware } from 'nuxt/app';
import type { Pojo } from '~/shared/types/utils';
import { umbraco, type IContent } from '~/umbraco/client/client';
import type { INavigation } from '~/umbraco/types/document-types/global/navigation';

/**
 * Nuxt middleware to inject the requested Umbraco content item into the route
 * object.
 */
const middleware: RouteMiddleware = async (to) => {
	const { data, error } = await useAsyncData(to.path, () =>
		Promise.all([getNavigation(), getContent(to.path)] as const)
	);

	if (error.value) {
		throw error.value;
	}

	const [navigation, page] = data.value!;

	to.meta.global = {
		navigation
	};

	to.meta.page = page;
};

export default middleware;

export type Data<P extends Pojo = Pojo> = {
	global: {
		navigation: IContent<INavigation>;
	};
	page: IContent<P>;
};

/**
 * Returns the Umbraco content item for a given path by calling the API client generated by
 * openapi-typescript.
 * @param path - The path.
 * @returns The content item, or null.
 */
const getContent = async (path: string): Promise<IContent> => {
	const { data, error } = await umbraco.GET(
		'/umbraco/delivery/api/v2/content/item/{path}',
		{
			params: {
				path: { path }
			}
		}
	);

	if (error) {
		throw createError({
			statusCode: error.status ?? 500,
			statusMessage: error.title ?? 'Unknown error, please try again later'
		});
	}

	return data;
};

/**
 * Returns the Umbraco navigation content item by calling the API client generated by
 * openapi-typescript.
 * @returns The navigation content item.
 */
const getNavigation = async (): Promise<IContent<INavigation>> =>
	getContent('/navigation') as Promise<IContent<INavigation>>;
