import createClient from 'openapi-fetch';

/**
 * Umbraco HTTP client.
 */
const client = createClient<paths>({
	// TODO: update depending on environment
	baseUrl: 'http://localhost:55235'
});

/**
 * Returns the Umbraco content item for a given path by calling the API client generated by
 * openapi-typescript.
 * @param path - Path of the Umbraco content item.
 * @returns Umbraco content item, or null.
 */
export const getUmbracoContent = async <P extends Pojo = Pojo>(
	path: string
): Promise<IUmbracoContent<P>> => {
	const { data, error } = await client.GET('/umbraco/delivery/api/v2/content/item/{path}', {
		params: {
			path: { path }
		}
	});

	if (error) {
		throw createError({
			statusCode: error.status ?? 500,
			statusMessage: error.title ?? 'Unknown error, please try again later'
		});
	}

	// TODO: proper validation

	return data as IUmbracoContent<P>;
};
